---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg"
    configmap.fabric8.io/update-on-change: "fabric8"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    expose: "true"
    version: "${project.version}"
    group: "io.fabric8.apps"
  name: "fabric8"
spec:
  replicas: 1
  selector:
    provider: "fabric8"
    group: "${project.groupId}"
    project: "${project.artifactId}"
    expose: "true"
  triggers:
  - type: "ConfigChange"
  template:
    metadata:
      labels:
        provider: "fabric8"
        group: "${project.groupId}"
        project: "${project.artifactId}"
        expose: "true"
        version: "${project.version}"
    spec:
      containers:
      - env:
        - name: "OAUTH_AUTHORIZE_URI"
          valueFrom:
            configMapKeyRef:
              key: "oauth-authorize-uri"
              name: "fabric8"
        - name: "GITHUB_OAUTH_CLIENT_SECRET"
          valueFrom:
            configMapKeyRef:
              key: "github-oauth-client-secret"
              name: "fabric8"
        - name: "GITHUB_OAUTH_CLIENT_ID"
          valueFrom:
            configMapKeyRef:
              key: "github-oauth-client-id"
              name: "fabric8"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: OAUTH_CLIENT_ID
          value: fabric8
        - name: OAUTH_PROVIDER
          value: openshift
        image: "fabric8/fabric8-console:${project.version}"
        name: "fabric8-container"
        ports:
        - containerPort: 9090
          name: "http"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
